# Generated by Django 4.2 on 2023-05-16 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticia', '0007_alter_autor_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='likes',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
