# Generated by Django 4.2 on 2023-05-16 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticia', '0009_alter_noticia_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticia',
            name='likes',
        ),
    ]
